### PR TITLE
Star Trek game

### PR DESCRIPTION
**Pull request by haiqu**

### CODE REVIEW

**Comment by ultibohub** [comment]
Testing on a RPi3 (with keyboard available) shows that the implementation of Read() and ReadLn() in Ultibo core has an issue with correct handling of line endings. Currentlyresolving that issue before merging this pull request.

**Comment by haiqu** [comment]
Had a similar problem with some code last week when translated from Linux. The 'LineEnding' constant came in handy but no way in hades could I write a routine that reliably read a single Char from a file. I eventually had to use the inbuilt 'ReadLn' which miraculously worked perfectly.

**Comment by haiqu** [comment]
Clarification of copyright for P5 package, from whence this game originated: 

http://www.standardpascal.org/rights.html

**Comment by ultibohub** [comment]
Thanks for that, given that they present the entire resource as public domain then we'll go with that and point to the them as the origin of the example for the purpose of giving credit.

**Comment by haiqu** [comment]
Just added the test program I've been using for the TFT display, thought it might be of use.

**Pull request closed without merging**
